import { createWalletClient, http, createPublicClient } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { readFileSync } from "fs";
import { resolve } from "path";
import { pharosTestnet } from "../src/client";

// Compiled contract artifacts (generated by `forge build`)
function loadArtifact(name: string) {
    const path = resolve(__dirname, `../out/${name}.sol/${name}.json`);
    const artifact = JSON.parse(readFileSync(path, "utf-8"));
    return { abi: artifact.abi, bytecode: artifact.bytecode.object as `0x${string}` };
}

async function main() {
    const privateKey = process.env.PRIVATE_KEY;
    if (!privateKey) throw new Error("PRIVATE_KEY env var required");

    const account = privateKeyToAccount(privateKey as `0x${string}`);
    const wallet = createWalletClient({ account, chain: pharosTestnet, transport: http() });
    const client = createPublicClient({ chain: pharosTestnet, transport: http() });

    console.log("Deploying from:", account.address);

    // 1. Deploy AgentRegistry
    const registry = loadArtifact("AgentRegistry");
    const registryHash = await wallet.deployContract({
        abi: registry.abi,
        bytecode: registry.bytecode,
    });
    const registryReceipt = await client.waitForTransactionReceipt({ hash: registryHash });
    const registryAddress = registryReceipt.contractAddress!;
    console.log("AgentRegistry deployed:", registryAddress);

    // 2. Deploy LeashGatedTransfer with registry address
    const transfer = loadArtifact("LeashGatedTransfer");
    const transferHash = await wallet.deployContract({
        abi: transfer.abi,
        bytecode: transfer.bytecode,
        args: [registryAddress],
    });
    const transferReceipt = await client.waitForTransactionReceipt({ hash: transferHash });
    const transferAddress = transferReceipt.contractAddress!;
    console.log("LeashGatedTransfer deployed:", transferAddress);

    // 3. Authorize LeashGatedTransfer to write reputation
    const { request } = await client.simulateContract({
        account,
        address: registryAddress,
        abi: registry.abi,
        functionName: "setAuthorized",
        args: [transferAddress, true],
    });
    await wallet.writeContract(request);
    console.log("LeashGatedTransfer authorized as reputation writer");

    console.log("\n--- Add to your .env ---");
    console.log(`REGISTRY_ADDRESS=${registryAddress}`);
    console.log(`TRANSFER_ADDRESS=${transferAddress}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
